name: Bot Status Monitor

on:
  schedule:
    # Щогодинна перевірка статусу
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check bot responsiveness
      run: |
        echo "🔍 Checking bot status at $(date)"
        
        # Перевірка основного ендпоінту
        if curl -f --max-time 30 https://ferrik-bot-zvev.onrender.com/keep-alive; then
          echo "✅ Bot is responsive"
        else
          echo "❌ Bot not responding, may be sleeping"
          
          # Додатковий пінг для пробудження
          echo "🔄 Attempting to wake up bot..."
          for i in {1..3}; do
            curl --max-time 10 https://ferrik-bot-zvev.onrender.com/ || true
            sleep 10
          done
        fi
        
    - name: Generate status report
      run: |
        echo "📊 Bot Status Report - $(date)"
        echo "Service URL: https://ferrik-bot-zvev.onrender.com"
        echo "Render Dashboard: https://dashboard.render.com/"
        echo "GitHub Actions: https://github.com/${{ github.repository }}/actions"